AllCops:
  Exclude:
    - Gemfile
    - Guardfile
    - devise_rails_api_authentication.gemspec
    - spec/**/*
Style/MultilineBlockChain:
  Enabled: false
Style/MultilineOperationIndentation:
  Enabled: false
Documentation:
  Enabled: false
